name: UploadNone

on:
  push:
    branches:
      - test_workflow
  pull_request:

jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
      - name: Wait
        run: sleep 20
  upload:
    runs-on: ubuntu-latest
    needs: wait
    steps:
      - name: Dump
        run: |
          mkdir artifact
          echo $GITHUB_SHA > artifact/sha
